[package]
name = "juno-tokenfactory-types"
description = "The execute msg types for Juno's TokenFactory module."
license = "MIT OR Apache-2.0"
version = "0.1.0"
authors = ["Reece Williams <reecepbcups@gmail.com>"]
edition = "2018"

[dependencies]
cosmwasm-schema = "1.1"
cosmwasm-std = "1.1"
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
token-bindings = "0.11.0"

[dev-dependencies]