name: strangelove ictest

on: [push]

# Cancel task if a new commit is pushed while old workflows run
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: 1.19

jobs:
  e2e-setup:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - uses: actions/checkout@v3

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      # Install Rust
      - name: Install latest nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true
  


      # Install depends (Can't cache docker image builds unless there is a cosmwasm/workspace-optimizer workflow)
      # - name: Rust Dependencies Cache
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/.cargo/registry/index/
      #       ~/.cargo/registry/cache/
      #       ~/.cargo/git/db/
      #       target/
      #       artifacts/
      #     key: ${{ runner.os }}-cargo-with-artifacts-${{ hashFiles('**/Cargo.lock') }}

      # TODO install go and cache test/ sub folder go.sum
      
      - name: Build the artifact
        run: make compile

      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" | tr '/' '_' >>$GITHUB_OUTPUT
        id: extract_branch
      
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3        
        with:
          name: ${{ steps.extract_branch.outputs.branch }}-contracts
          retention-days: 1
          path: |
            artifacts
            !artifacts/*.txt

  test-basic:
    runs-on: ubuntu-latest
    needs: e2e-setup
    steps:
      # - name: Set up Go ${{ env.GO_VERSION }}
      #   uses: actions/setup-go@v3
      #   with:
      #     go-version: ${{ env.GO_VERSION }}
      #   id: go
      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      # TODO: Put this in the parent? does it share here for env variables?
      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" | tr '/' '_' >>$GITHUB_OUTPUT
        id: extract_branch

      - name: checkout chain
        uses: actions/checkout@v3        

      - uses: actions/download-artifact@v3
        with:
          name: ${{ steps.extract_branch.outputs.branch }}-contracts
          path: artifacts

      - run: make ictest-basic